package: cloud.lazycat.app.gobackup
version: 2.14.0
name: GoBackup
description: "数据库、配置文件备份工具"
min_os_version: "1.5.0"
homepage: https://github.com/gobackup/gobackup
author: rubychina

locales:
  zh:
    name: GoBackup
    description: "一个为中小型服务器而设计备份工具，内置计划任务，帮你定时备份数据库、配置文件，通过导出、打包压缩，最终存储到外部云存储（如 FTP、SCP、S3、GCS、Aliyun OSS 等）"
  en:
    name: GoBackup
    description: "A backup tool designed for small and medium servers with built-in scheduled tasks, backing up databases and config files and storing them to cloud storage (FTP, SCP, S3, GCS, Aliyun OSS, etc.)"
